version: '3.8'

services:
  discuzq:
    image: websoft9dev/akeneo:${APP_VERSION}
    container_name: ${APP_NAME}
    ports:
      - ${APP_PORT}:80
    volumes:
      - discuzq:/var/www/html
    restart: always
    environment:
      AKENEO_MYSQL_DATABASE: ${DB_MYSQL_NAME}
      AKENEO_MYSQL_USER: ${DB_MYSQL_USER}
      AKENEO_MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
      AKENEO_MYSQL_HOST: ${DB_MYSQL_HOST}
      AKENEO_SITENAME: ${APP_SITENAME}
      AKENEO_USER: ${APP_ADMIN_NAME}
      AKENEO_PASSWORD: ${APP_ADMIN_PASSWORD}
      
  mysql:
    image: mysql:${DB_MYSQL_VERSION}
    container_name: ${APP_NAME}-mysql
    restart: always
    ports:
     - ${DB_MYSQL_PORT}:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_MYSQL_NAME}
      MYSQL_USER: ${DB_MYSQL_USER}
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_PASSWORD}

networks:
  default:
      name: ${APP_NAME}

volumes:
  akeneo:
  mysql: